# Generated by Django 5.2.17 on 2026-08-17 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('all_day', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('source', models.CharField(default='local', max_length=50)),
            ],
            options={
                'ordering': ['start'],
            },
        ),
    ]
