# Generated by Django 5.2.17 on 2026-08-17 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0004_event_external_uid_calendarsource_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarsource',
            name='url',
            field=models.CharField(max_length=500),
        ),
    ]
